package main

// Small CLI tool that generates Go types from the `components.schemas` section
// of an OpenAPI v3 JSON file (e.g. `openrouterapi.json`).
//
// Usage:
//   go run ./pkg/openrouter/generate_types.go -spec=openrouterapi.json -out=./pkg/openrouter/types_openrouter_generated.go
//
// Notes:
// - This generator implements a conservative subset of JSON Schema -> Go mapping.
// - It handles object properties, arrays, $ref to components/schemas, string enums,
//   additionalProperties => map[string]T, and maps date/time strings to time.Time.
// - For non-required fields the generator uses pointer types to enable `omitempty`
//   and nil semantics.

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

func main() {
	specPath := flag.String("spec", "openrouterapi.json", "path to OpenAPI JSON specification")
	outPath := flag.String("out", "", "output file (defaults to stdout)")
	pkgName := flag.String("package", "openrouter", "package name for generated file")
	flag.Parse()

	var w io.Writer
	var outFile *os.File
	var err error
	if *outPath == "" {
		w = os.Stdout
	} else {
		err = os.MkdirAll(filepath.Dir(*outPath), 0o755)
		if err != nil {
			fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
			os.Exit(2)
		}
		outFile, err = os.Create(*outPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "create output: %v\n", err)
			os.Exit(2)
		}
		defer outFile.Close()
		w = outFile
	}

	src, err := GenerateTypesFromSpec(*specPath, *pkgName)
	if err != nil {
		fmt.Fprintf(os.Stderr, "generate: %v\n", err)
		os.Exit(1)
	}

	// Write formatted source
	if _, err := w.Write(src); err != nil {
		fmt.Fprintf(os.Stderr, "write output: %v\n", err)
		os.Exit(1)
	}

	if outFile != nil {
		fmt.Fprintf(os.Stderr, "wrote %s\n", *outPath)
	}
}

// GenerateTypesFromSpec reads the OpenAPI JSON file at specPath and returns
// formatted Go source bytes with types derived from components.schemas.
func GenerateTypesFromSpec(specPath, pkg string) ([]byte, error) {
	b, err := ioutil.ReadFile(specPath)
	if err != nil {
		return nil, fmt.Errorf("read spec %q: %w", specPath, err)
	}
	var root map[string]interface{}
	if err := json.Unmarshal(b, &root); err != nil {
		return nil, fmt.Errorf("unmarshal spec: %w", err)
	}
	components, _ := root["components"].(map[string]interface{})
	if components == nil {
		return nil, fmt.Errorf("no components section found in spec")
	}
	schemas, _ := components["schemas"].(map[string]interface{})
	if schemas == nil {
		return nil, fmt.Errorf("no components.schemas found in spec")
	}

	ctx := &genContext{
		schemas: schemas,
		defs:    map[string]string{},
		imports: map[string]bool{},
		seen:    map[string]bool{},
	}

	// Deterministic order
	var keys []string
	for k := range schemas {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	// Generate top-level definitions
	for _, k := range keys {
		name := toTypeName(k)
		if ctx.seen[name] {
			continue
		}
		raw := schemas[k]
		m, _ := raw.(map[string]interface{})
		if m == nil {
			ctx.defs[name] = fmt.Sprintf("type %s interface{}\n", name)
			ctx.seen[name] = true
			continue
		}
		ctx.generateTopLevel(name, m)
	}

	// Compose output buffer
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by generate_types.go; DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg)

	// imports
	if len(ctx.imports) > 0 {
		fmt.Fprintf(&buf, "import (\n")
		var imps []string
		for imp := range ctx.imports {
			imps = append(imps, imp)
		}
		sort.Strings(imps)
		for _, imp := range imps {
			fmt.Fprintf(&buf, "\t%q\n", imp)
		}
		fmt.Fprintf(&buf, ")\n\n")
	}

	// write definitions in deterministic order
	var defNames []string
	for n := range ctx.defs {
		defNames = append(defNames, n)
	}
	sort.Strings(defNames)
	for _, n := range defNames {
		fmt.Fprintf(&buf, "%s\n\n", ctx.defs[n])
	}

	// Format
	src, err := format.Source(buf.Bytes())
	if err != nil {
		// Return unformatted contents if formatting fails, but include error to stderr
		fmt.Fprintf(os.Stderr, "go/format failed: %v\n", err)
		return buf.Bytes(), nil
	}
	return src, nil
}

// genContext holds generation state.
type genContext struct {
	schemas map[string]interface{}
	defs    map[string]string
	imports map[string]bool
	seen    map[string]bool
}

// generateTopLevel creates a named type for a top-level schema.
func (g *genContext) generateTopLevel(typeName string, schema map[string]interface{}) string {
	if g.seen[typeName] {
		return typeName
	}

	// enums
	if enumVals, ok := schema["enum"]; ok {
		if arr, ok := enumVals.([]interface{}); ok && len(arr) > 0 {
			underlying := "string"
			if t, ok := schema["type"].(string); ok && t != "" {
				underlying = jsonTypeToGoBasicType(t, "")
			}
			var b bytes.Buffer
			fmt.Fprintf(&b, "type %s %s\n\n", typeName, underlying)
			fmt.Fprintf(&b, "const (\n")
			for i, v := range arr {
				val := fmt.Sprintf("%v", v)
				constName := fmt.Sprintf("%s_%s", typeName, toConstName(val))
				fmt.Fprintf(&b, "\t%s %s = %q\n", constName, typeName, val)
				_ = i
			}
			fmt.Fprintf(&b, ")\n")
			g.defs[typeName] = b.String()
			g.seen[typeName] = true
			return typeName
		}
	}

	// object -> struct
	if t, ok := schema["type"].(string); ok && t == "object" {
		props, _ := schema["properties"].(map[string]interface{})
		required := stringSliceFromInterface(schema["required"])
		// If no properties but additionalProperties exists, emit map alias
		if (props == nil || len(props) == 0) && schema["additionalProperties"] != nil {
			// map type
			if ap, ok := schema["additionalProperties"].(map[string]interface{}); ok {
				elem := g.resolveSchemaType(ap, typeName+"Additional")
				g.defs[typeName] = fmt.Sprintf("type %s map[string]%s\n", typeName, elem)
			} else {
				g.defs[typeName] = fmt.Sprintf("type %s map[string]interface{}\n", typeName)
			}
			g.seen[typeName] = true
			return typeName
		}

		var b bytes.Buffer
		fmt.Fprintf(&b, "type %s struct {\n", typeName)
		// properties in stable order
		var pnames []string
		for pn := range props {
			pnames = append(pnames, pn)
		}
		sort.Strings(pnames)
		for _, pn := range pnames {
			pv, _ := props[pn].(map[string]interface{})
			fieldName := toTypeName(pn)
			goType := g.resolveSchemaType(pv, typeName+fieldName)
			isReq := contains(required, pn)
			// Make pointer for optional fields (omitempty)
			if !isReq {
				// Avoid double pointer
				if !strings.HasPrefix(goType, "*") && !strings.HasPrefix(goType, "[]") && !strings.HasPrefix(goType, "map[") && goType != "interface{}" {
					goType = "*" + goType
				}
			}
			tag := fmt.Sprintf("`json:%q,omitempty`", pn)
			desc := ""
			if d, ok := pv["description"].(string); ok && d != "" {
				desc = " // " + strings.ReplaceAll(strings.TrimSpace(d), "\n", " ")
			}
			fmt.Fprintf(&b, "\t%s %s %s%s\n", fieldName, goType, tag, desc)
		}
		// additionalProperties -> map field
		if ap, ok := schema["additionalProperties"]; ok {
			switch v := ap.(type) {
			case bool:
				if v {
					fmt.Fprintf(&b, "\tAdditionalProperties map[string]interface{} `json:\"-\"`\n")
				}
			case map[string]interface{}:
				elem := g.resolveSchemaType(v, typeName+"AdditionalProperty")
				fmt.Fprintf(&b, "\tAdditionalProperties map[string]%s `json:\"-\"`\n", elem)
			}
		}
		fmt.Fprintf(&b, "}\n")
		g.defs[typeName] = b.String()
		g.seen[typeName] = true
		return typeName
	}

	// array alias
	if t, ok := schema["type"].(string); ok && t == "array" {
		items, _ := schema["items"].(map[string]interface{})
		elem := g.resolveSchemaType(items, typeName+"Item")
		g.defs[typeName] = fmt.Sprintf("type %s []%s\n", typeName, elem)
		g.seen[typeName] = true
		return typeName
	}

	// allOf: try to merge into struct
	if allOf, ok := schema["allOf"].([]interface{}); ok && len(allOf) > 0 {
		var b bytes.Buffer
		fmt.Fprintf(&b, "type %s struct {\n", typeName)
		for _, part := range allOf {
			if pm, ok := part.(map[string]interface{}); ok {
				if ref, ok := pm["$ref"].(string); ok {
					refType := refToTypeName(ref)
					fmt.Fprintf(&b, "\t%s\n", refType)
				} else if t, ok := pm["type"].(string); ok && t == "object" {
					props, _ := pm["properties"].(map[string]interface{})
					req := stringSliceFromInterface(pm["required"])
					var pnames []string
					for pn := range props {
						pnames = append(pnames, pn)
					}
					sort.Strings(pnames)
					for _, pn := range pnames {
						ps, _ := props[pn].(map[string]interface{})
						fieldName := toTypeName(pn)
						goType := g.resolveSchemaType(ps, typeName+fieldName)
						if !contains(req, pn) {
							if !strings.HasPrefix(goType, "*") && goType != "interface{}" && !strings.HasPrefix(goType, "[]") && !strings.HasPrefix(goType, "map[") {
								goType = "*" + goType
							}
						}
						tag := fmt.Sprintf("`json:%q,omitempty`", pn)
						fmt.Fprintf(&b, "\t%s %s %s\n", fieldName, goType, tag)
					}
				}
			}
		}
		fmt.Fprintf(&b, "}\n")
		g.defs[typeName] = b.String()
		g.seen[typeName] = true
		return typeName
	}

	// fallback: basic type alias or interface{}
	if t, ok := schema["type"].(string); ok && t != "" {
		if t == "string" {
			if f, _ := schema["format"].(string); f == "date-time" || f == "date" {
				g.imports["time"] = true
				g.defs[typeName] = fmt.Sprintf("type %s time.Time\n", typeName)
				g.seen[typeName] = true
				return typeName
			}
		}
		goBasic := jsonTypeToGoBasicType(t, "")
		g.defs[typeName] = fmt.Sprintf("type %s %s\n", typeName, goBasic)
		g.seen[typeName] = true
		return typeName
	}

	// ultimate fallback
	g.defs[typeName] = fmt.Sprintf("type %s interface{}\n", typeName)
	g.seen[typeName] = true
	return typeName
}

// resolveSchemaType returns a Go type name (possibly creating inline types).
func (g *genContext) resolveSchemaType(schema map[string]interface{}, nameHint string) string {
	if schema == nil {
		return "interface{}"
	}
	// $ref
	if ref, ok := schema["$ref"].(string); ok {
		return refToTypeName(ref)
	}
	// enum inline -> create named type
	if enumVals, ok := schema["enum"]; ok {
		if arr, ok := enumVals.([]interface{}); ok && len(arr) > 0 {
			tn := nameHint
			if tn == "" {
				tn = "Enum"
			}
			tn = uniqueTypeName(tn)
			var b bytes.Buffer
			underlying := "string"
			if t, ok := schema["type"].(string); ok && t != "" {
				underlying = jsonTypeToGoBasicType(t, "")
			}
			fmt.Fprintf(&b, "type %s %s\n\n", tn, underlying)
			fmt.Fprintf(&b, "const (\n")
			for _, v := range arr {
				val := fmt.Sprintf("%v", v)
				constName := fmt.Sprintf("%s_%s", tn, toConstName(val))
				fmt.Fprintf(&b, "\t%s %s = %q\n", constName, tn, val)
			}
			fmt.Fprintf(&b, ")\n")
			g.defs[tn] = b.String()
			g.seen[tn] = true
			return tn
		}
	}

	// arrays
	if t, ok := schema["type"].(string); ok && t == "array" {
		items, _ := schema["items"].(map[string]interface{})
		elem := g.resolveSchemaType(items, nameHint+"Item")
		return "[]" + elem
	}

	// object inline -> create a named inline struct
	if t, ok := schema["type"].(string); ok && t == "object" {
		tn := nameHint
		if tn == "" {
			tn = "InlineObject"
		}
		tn = uniqueTypeName(tn)
		props, _ := schema["properties"].(map[string]interface{})
		required := stringSliceFromInterface(schema["required"])
		var b bytes.Buffer
		fmt.Fprintf(&b, "type %s struct {\n", tn)
		var pnames []string
		for k := range props {
			pnames = append(pnames, k)
		}
		sort.Strings(pnames)
		for _, p := range pnames {
			ps, _ := props[p].(map[string]interface{})
			fieldName := toTypeName(p)
			goType := g.resolveSchemaType(ps, tn+fieldName)
			if !contains(required, p) {
				if !strings.HasPrefix(goType, "*") && goType != "interface{}" && !strings.HasPrefix(goType, "[]") && !strings.HasPrefix(goType, "map[") {
					goType = "*" + goType
				}
			}
			tag := fmt.Sprintf("`json:%q,omitempty`", p)
			desc := ""
			if d, ok := ps["description"].(string); ok && d != "" {
				desc = " // " + strings.ReplaceAll(strings.TrimSpace(d), "\n", " ")
			}
			fmt.Fprintf(&b, "\t%s %s %s%s\n", fieldName, goType, tag, desc)
		}
		fmt.Fprintf(&b, "}\n")
		g.defs[tn] = b.String()
		g.seen[tn] = true
		return tn
	}

	// basic primitives
	if t, ok := schema["type"].(string); ok && t != "" {
		if t == "string" {
			if f, _ := schema["format"].(string); f == "date-time" || f == "date" {
				g.imports["time"] = true
				return "time.Time"
			}
		}
		return jsonTypeToGoBasicType(t, "")
	}

	// additionalProperties as map
	if ap, ok := schema["additionalProperties"]; ok {
		switch v := ap.(type) {
		case bool:
			if v {
				return "map[string]interface{}"
			}
		case map[string]interface{}:
			elem := g.resolveSchemaType(v, nameHint+"Additional")
			return "map[string]" + elem
		}
	}

	// fallback
	return "interface{}"
}

// jsonTypeToGoBasicType maps JSON Schema primitive types to Go basic types.
func jsonTypeToGoBasicType(jsonType, format string) string {
	switch jsonType {
	case "string":
		return "string"
	case "integer":
		return "int"
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	case "object":
		return "map[string]interface{}"
	case "array":
		return "[]interface{}"
	default:
		return "interface{}"
	}
}

// refToTypeName maps a local $ref like "#/components/schemas/Foo" to "Foo".
func refToTypeName(ref string) string {
	parts := strings.Split(ref, "/")
	raw := parts[len(parts)-1]
	return toTypeName(raw)
}

// toTypeName converts arbitrary schema keys to exported Go identifiers.
func toTypeName(s string) string {
	// If contains separators, take last segment
	if idx := strings.LastIndexAny(s, "./#"); idx != -1 {
		s = s[idx+1:]
	}
	re := regexp.MustCompile("[^A-Za-z0-9]+")
	parts := re.Split(s, -1)
	var out string
	for _, p := range parts {
		if p == "" {
			continue
		}
		out += strings.Title(p)
	}
	if out == "" {
		out = "T"
	} else if !regexp.MustCompile("^[A-Za-z]").MatchString(out) {
		out = "T" + out
	}
	return out
}

// toConstName makes a safe constant suffix from a string value.
func toConstName(v string) string {
	re := regexp.MustCompile("[^A-Za-z0-9]+")
	s := re.ReplaceAllString(v, "_")
	s = strings.Trim(s, "_")
	if s == "" {
		s = "Val"
	}
	// Uppercase for readability
	return strings.ToUpper(s)
}

var _uniqueNames = map[string]int{}

// uniqueTypeName returns a name unique within this generator run.
func uniqueTypeName(base string) string {
	if _, ok := _uniqueNames[base]; !ok {
		_uniqueNames[base] = 1
		return base
	}
	_uniqueNames[base]++
	return fmt.Sprintf("%s_%d", base, _uniqueNames[base])
}

// stringSliceFromInterface converts []interface{} -> []string
// stringSliceFromInterface converts common slice-like interface{} values to []string.
//
// It accepts either []interface{} (the common result of unmarshaled JSON arrays)
// or []string directly. For other types it returns nil.
func stringSliceFromInterface(v interface{}) []string {
	if v == nil {
		return nil
	}

	switch vv := v.(type) {
	case []interface{}:
		out := make([]string, 0, len(vv))
		for _, x := range vv {
			if s, ok := x.(string); ok {
				out = append(out, s)
			}
		}
		return out
	case []string:
		// return a copy to avoid surprising callers that mutate the slice
		out := make([]string, len(vv))
		copy(out, vv)
		return out
	default:
		return nil
	}
}

func contains(arr []string, s string) bool {
	if len(arr) == 0 {
		return false
	}
	for _, v := range arr {
		if v == s {
			return true
		}
	}
	return false
}
